name: Deploy to GitHub Pages

# Chạy workflow này khi có push lên nhánh main
on:
  push:
    branches:
      - main # Hoặc tên nhánh chính của bạn (master, develop, etc.)
  # Cho phép chạy workflow này thủ công từ tab Actions
  workflow_dispatch:

# Thiết lập quyền cho GITHUB_TOKEN để cho phép triển khai lên GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Cho phép chỉ một lần triển khai đồng thời, hủy bỏ các lần chạy đang thực hiện hoặc đang chờ xử lý
# của workflow này nhưng cho cùng một nhóm đồng thời.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # URL sẽ hiển thị trong môi trường của job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action để checkout code từ repository

      - name: Setup Pages
        uses: actions/configure-pages@v4 # Action để cấu hình GitHub Pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # Action để tải lên artifact cho GitHub Pages
        with:
          # Tải lên toàn bộ thư mục gốc (nơi chứa index.html)
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment # Cần ID để tham chiếu đến output của step này
        uses: actions/deploy-pages@v3 # Action để triển khai lên GitHub Pages